j-mueller/sc-tools

changelog.md
src/devnet/lib/Convex/Devnet/CardanoNode.hs
src/devnet/lib/Convex/Devnet/NodeQueries.hs

add-slot-lenght-to-queries

---

changelog.md
src/base/lib/Convex/Class.hs
src/devnet/convex-devnet.cabal
src/devnet/lib/Convex/Devnet/CardanoNode.hs
src/devnet/lib/Convex/Devnet/Wallet.hs
src/trading-bot/lib/Convex/TradingBot/NodeClient/OrderClient.hs

Generic result type

---

changelog.md
src/base/convex-base.cabal
src/base/lib/Convex/Lenses.hs
src/base/lib/Convex/Utils.hs
src/coin-selection/convex-coin-selection.cabal
src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/lib/Convex/MockChain/CoinSelection.hs
src/coin-selection/lib/Convex/Query.hs
src/devnet/lib/Convex/Devnet/Wallet.hs
src/node-client/convex-node-client.cabal
src/wallet/convex-wallet.cabal
src/wallet/lib/Convex/Wallet/API.hs
src/wallet/lib/Convex/Wallet/Cli.hs
src/wallet/lib/Convex/Wallet/Cli/Command.hs
src/wallet/lib/Convex/Wallet/Cli/Config.hs
src/wallet/lib/Convex/Wallet/NodeClient/BalanceClient.hs
src/wallet/lib/Convex/Wallet/Operator.hs

* Add Convex.Wallet.Operator
* Add Wallet HTTP server
* Add Convex.Query for UTxO queries

coin-selection: Add operator module, wallet server

---

changelog.md
src/coin-selection/lib/Convex/BuildTx.hs

Introducing mintPlutusV2Ref function to support reference scripts for minting policies

Adding mintPlutusV2Ref function

---

changelog.md
src/coin-selection/lib/Convex/BuildTx.hs

Introduction of `mintPlutusV2Ref` function to support reference script for minting policies

Adding mintPlutusV2Ref function 

---

src/base/lib/Convex/Utxos.hs

Exposes extractBabbageTx to allow extraction of events by transaction.

Expose extractBabbageTx

---

.github/workflows/ci-linux.yaml
cabal.project
src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/lib/Convex/Query.hs
src/devnet/lib/Convex/Devnet/NodeQueries.hs
src/node-client/lib/Convex/NodeClient/Fold.hs
src/node-client/lib/Convex/NodeClient/Types.hs
src/un-ada/lib/UnAda/OffChain/Transaction.hs
src/un-ada/lib/UnAda/OnChain/Types.hs

This PR address the haddock build for there 3 projects. You should be able to reproduce the problem using:
`cabal haddock -j convex-node-client convex-coin-selection convex-devnet`
On this branch, you should see those errors fixed

Fix haddock comments

---

changelog.md
src/base/lib/Convex/BuildTx.hs

Fixing minimum UTxO value computation (main) 

---

changelog.md
src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/test/Spec.hs

coin-selection: Fix a bug where coin selection failed on singleton multi-asset output

---

changelog.md
src/base/lib/Convex/BuildTx.hs
src/coin-selection/convex-coin-selection.cabal
src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/lib/Convex/MockChain/CoinSelection.hs
src/coin-selection/test/Scripts.hs
src/coin-selection/test/Scripts/MatchingIndex.hs
src/coin-selection/test/Spec.hs
src/un-ada/lib/UnAda/OffChain/Transaction.hs

* Add witness map to tx build
* Add a test for the index lookup function
* Add reference inputs

Add witness map to tx build (#121)

---

changelog.md
src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/test/Spec.hs
src/wallet/lib/Convex/Wallet.hs

Build transactions with all-mixed-inputs

---

changelog.md
src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/test/Spec.hs
src/wallet/lib/Convex/Wallet.hs

* Consider mixed inputs when balancing WIP
* Add failing test
* Fix coin selection

Build transactions with all-mixed-inputs (#126)

---

src/base/lib/Convex/BuildTx.hs
src/base/lib/Convex/Class.hs
src/mockchain/convex-mockchain.cabal
src/mockchain/lib/Convex/MockChain.hs
src/node-client/lib/Convex/NodeClient/WaitForTxnClient.hs

Query stake addresses

---

src/base/lib/Convex/BuildTx.hs

Build was not attempted due to not having ghc 9 env setup

Reader instance for BuildTxT

---

src/node-client/convex-node-client.cabal
src/node-client/lib/Convex/NodeClient/Fold.hs
src/node-client/lib/Convex/NodeClient/WaitForTxnClient.hs
src/wallet/lib/Convex/Wallet/NodeClient/BalanceClient.hs

foldClient with ledger state #135

---

src/base/lib/Convex/BuildTx.hs
src/coin-selection/test/Scripts.hs

Also fix spelling mistake in find/lookupIndexWithrawal

Add some utility functions to build script witnesses.

---

cabal.project
flake.lock
flake.nix

Minimal setup for a nix flake (depends only on haskell.nix)

Add minimal nix flake

---

src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/lib/Convex/CoinSelection/Class.hs
src/devnet/lib/Convex/Devnet/CardanoNode.hs
src/devnet/lib/Convex/Devnet/CardanoNode/Types.hs
src/devnet/lib/Convex/Devnet/Wallet.hs
src/devnet/lib/Convex/Devnet/WalletServer.hs
src/devnet/test/Spec.hs

* Add instance for TracingBalancingT, BalancingT
* Fix formatting

Fix stylish-haskell; more instances

---

src/coin-selection/lib/Convex/CoinSelection.hs
src/devnet/lib/Convex/Devnet/CardanoNode.hs

Closes #161
I'll provide a backport to 1.35.4 once this is merged.

Signature count fix

---

src/node-client/lib/Convex/NodeClient/WaitForTxnClient.hs

Port of f1a400dd4038fa50581adc04269f77a5869886a9 / #176  to `main`

Fix client waiting for failed Tx to appear

---

changelog.md
src/base/lib/Convex/BuildTx.hs
src/coin-selection/lib/Convex/CoinSelection.hs
src/coin-selection/lib/Convex/CoinSelection/Class.hs
src/coin-selection/lib/Convex/MockChain/CoinSelection.hs
src/coin-selection/lib/Convex/Query.hs
src/coin-selection/test/Spec.hs
src/devnet/lib/Convex/Devnet/CardanoNode.hs
src/devnet/lib/Convex/Devnet/Wallet.hs
src/un-ada/test/UnAda/Test/UnitTest.hs

Use TxBuilder in coin selection

---

src/base/lib/Convex/BuildTx.hs

Our use case required to build the redeemer using the tx body

Stake witness with tx body

---

.github/workflows/ci-linux.yaml
.github/workflows/gh-pages.yaml
README.md
cabal.project
fix-stylish-haskell.sh
flake.lock
flake.nix
src/base/lib/Convex/Class.hs
src/coin-selection/convex-coin-selection.cabal
src/coin-selection/lib/Convex/CoinSelection/Class.hs
src/coin-selection/lib/Convex/Query.hs
src/coin-selection/test/Spec.hs
src/mockchain/lib/Convex/MockChain.hs
src/node-client/lib/Convex/NodeClient/WaitForTxnClient.hs

MonadUtxoQuery nows returns the resolved datum alongside the TxOut.

Update GHC and change MonadUtxoQuery interface

---

src/base/lib/Convex/BuildTx.hs
src/base/lib/Convex/PlutusLedger.hs
src/base/lib/Convex/Utxos.hs
src/coin-selection/lib/Convex/CoinSelection.hs
src/optics/lib/Convex/CardanoApi/Lenses.hs
src/wallet/lib/Convex/Wallet.hs

Fix deprecation warnings

---

.github/workflows/ci-linux.yaml
README.md
cabal.project
flake.lock
src/base/convex-base.cabal
src/mockchain/lib/Convex/MockChain.hs
src/mockchain/lib/Convex/MockChain/Defaults.hs
src/optics/convex-optics.cabal

Update cardano-api to 10.0.0.0

---

cabal.project
src/base/lib/Convex/NodeQueries.hs
src/coin-selection/convex-coin-selection.cabal
src/coin-selection/test/Spec.hs
src/devnet/config/devnet/cardano-node.json
src/devnet/config/devnet/genesis-shelley.json
src/devnet/convex-devnet.cabal
src/devnet/lib/Convex/Devnet/CardanoNode/Types.hs
src/devnet/test/Devnet/Test/LatestEraTransitionSpec.hs
src/devnet/test/Devnet/Test/LatestEraTransitionSpec/PV2.hs
src/devnet/test/Devnet/Test/LatestEraTransitionSpec/PV3.hs
src/devnet/test/Spec.hs
src/mockchain/lib/Convex/MockChain/Defaults.hs

* Add unit test which shows that the protocol version of the devnet is 10.
* Add unit tests which verify that we can use latest Plutus primitives (readbit, writebit) in mockchain.
* Update PV3 cost model

Adding tests to make sure that the mockchain and devnet has been correctly updated to node version of Chang+1
