j-mueller/sc-tools

- changelog.md
- src/base/lib/Convex/Class.hs
- src/base/lib/Convex/Utils.hs
- src/devnet/lib/Convex/Devnet/NodeQueries.hs
- src/mockchain/lib/Convex/MockChain.hs
> add-querySlotNo-monadBlockchain

- changelog.md
- src/base/lib/Convex/Class.hs
- src/devnet/convex-devnet.cabal
- src/devnet/lib/Convex/Devnet/Wallet.hs
- src/trading-bot/lib/Convex/TradingBot/NodeClient/OrderClient.hs
> Throw error on send tx failure

- changelog.md
- src/base/lib/Convex/Lenses.hs
- src/coin-selection/lib/Convex/BuildTx.hs
> Additional PlutusV2 functions

- changelog.md
- src/base/lib/Convex/Lenses.hs
- src/coin-selection/lib/Convex/BuildTx.hs
> Additional Plutusv2 functions - main patch

- changelog.md
- src/base/lib/Convex/BuildTx.hs
> Fixing minimum UTxO value computation (node-1.35.4)

- .github/actions/haskell-setup-cached/action.yml
- .github/actions/setup-security-libs/action.yml
- .github/workflows/ci-linux.yaml
Following up https://github.com/j-mueller/sc-tools/pull/102#issuecomment-1862829972 here is the PR that:
- keeps only one workflow but different jobs
- adds documentation building into the CI
- adds some parallelization in 3 jobs (testing, building, documentation building)
- factorizes common logic in 2 composite actions
I went a bit further the scope you defined but I think this approach should optimize the pipeline
Here is the outcome:
- no cache (44mins)
https://github.com/albertodvp/sc-tools/actions/runs/7293690204
- cache hit: libsodium, libsecp256k1, dependencies (14mins)
https://github.com/albertodvp/sc-tools/actions/runs/7293491807
Let me know what you think of this approach and/or if you have any suggestions :relaxed:
> Parallelize ci workflow

- changelog.md
- src/coin-selection/lib/Convex/CoinSelection.hs
> Considering withdrawals and certificates in mapTxScriptWitnesses

- cabal.project
- src/base/lib/Convex/BuildTx.hs
- src/base/lib/Convex/Class.hs
- src/base/lib/Convex/NodeQueries.hs
- src/mockchain/lib/Convex/MockChain.hs
- src/node-client/lib/Convex/NodeClient/WaitForTxnClient.hs
> Query stake addresses #138

- src/node-client/lib/Convex/NodeClient/Types.hs
- src/wallet/lib/Convex/Wallet/Cli.hs
@j-mueller I think we should remove this part. I have not included the ledger state in this function in the back port version.
> Remove initial ledger state from runNodeClient

- flake.lock
- flake.nix
Here is a minimal flake for set up build tools to compile sc-tools libraries on the main branch.
I'd like to implement an validation process to ensure the effectiveness/correctness of the flake and to monitor for any potential breakages automatically. Specifically, I'm considering implementing a GHA pipeline that checks out the repository and builds it using nix. However, it's worth noting that this approach may result in longer CI runtimes (~40 minutes) due to the need for recompilation, particularly with the recent version of GHC.
If you are interested, I can create a workflow that is "non-blocking" and triggered by pushes to the master branch. Please let me know your thoughts on this approach😊
> Add minimal nix flake ghc964

- cabal.project
- flake.lock
- flake.nix
- src/coin-selection/lib/Convex/CoinSelection.hs
- src/coin-selection/lib/Convex/CoinSelection/Class.hs
- src/coin-selection/lib/Convex/MockChain/CoinSelection.hs
- src/coin-selection/lib/Convex/MockChain/Staking.hs
- src/coin-selection/lib/Convex/Query.hs
- src/coin-selection/test/Spec.hs
- src/devnet/lib/Convex/Devnet/CardanoNode.hs
- src/devnet/lib/Convex/Devnet/Wallet.hs
- src/un-ada/test/UnAda/Test/UnitTest.hs
- Added a new `ChangeOutputPosition` type and argument to most if not all of the balancing function to indicate the change output position when balancing a tx.
- Updated the flake to reflect with the recent cardano bump (I had to add `io-sim` to the `cabal.project` but I'm not sure if it will break non-nix build).
> Add change output position to balancing functions

- node-config/mainnet/mainnet-config.json
- node-config/mainnet/mainnet-conway-genesis.json
Adds a number of fields to `conway-genesis.json`. This is enough to get the node to start up (but the values aren't the final values for conway)
> Repair conway-genesis.json

- .github/workflows/nix.yaml
- README.md
- flake.nix
This PR adds:
- all the packages are build when `nix flake check`
- a new GHA job is introduced to check the nix flake works and the packages are correctly build with it: you can check the failures are triggered if:
- Code does not compile: https://github.com/albertodvp/sc-tools/actions/runs/10027059462/job/27712217717
- Flake has errors in it: https://github.com/albertodvp/sc-tools/actions/runs/10027054865/job/27712206225
Note:
I've set up a cachix cache for this, to make this work we would have to add a secret (auth token) for the cache to the github repo.
Unfortunately, this is needed because we currently don't have an official cache for the GHC version we are using (9.6.6).
See https://input-output-hk.github.io/haskell.nix/reference/supported-ghc-versions.html
I tried to recompile it …
> Gha job for nix

- changelog.md
- src/devnet/convex-devnet.cabal
- src/devnet/lib/Convex/Devnet/CardanoNode.hs
- src/devnet/lib/Convex/Devnet/CardanoNode/Types.hs
- src/devnet/lib/Convex/Devnet/NodeQueries.hs
- src/devnet/test/Spec.hs
* Enable conway hardfork in devnet using `Convex.Devnet.CardanoNode.Types.forkIntoConwayInEpoch`. This can be set to 0 to ensure that conway era is the default era from the start.
> Conway hardfork in devnet

- .pre-commit-config.yaml
- src/base/lib/Convex/BuildTx.hs
- src/base/lib/Convex/Class.hs
* Adds helpers `mintSimpleScriptAssets` & `spendSimpleScript` to build tx module.
* Fix `getTxs` returning `LedgerTx` type.
> Add simple script mint/spend

- .github/workflows/ci-linux.yaml
- README.md
- cabal.project
- src/devnet/test/Spec.hs
> cardano-node-9.2.1

- src/base/convex-base.cabal
- src/base/lib/Convex/BuildTx.hs
- src/base/lib/Convex/Eon.hs
- src/base/lib/Convex/PlutusLedger.hs
- src/base/test/Convex/PlutusLedgerSpec.hs
- src/coin-selection/convex-coin-selection.cabal
- src/coin-selection/lib/Convex/MockChain/Staking.hs
- src/coin-selection/test/Spec.hs
- src/devnet/config/devnet/genesis-shelley.json
- src/devnet/lib/Convex/Devnet/Wallet.hs
- src/devnet/test/Spec.hs
- src/mockchain/lib/Convex/MockChain/Defaults.hs
Add transaction building functions for correctly adding registration deregistration and delegation certificates in Conway era.
* Add functions for adding certificates in transactions such as:
* `addShelleyStakeCredentialRegistrationCertificatePreConway`
* `addShelleyStakeCredentialUnregistrationCertificatePreConway`
* `addShelleyStakeCredentialRegistrationCertificateInConway`
* `addShelleyStakeCredentialUnregistrationCertificateInConway`
* `addConwayStakeCredentialRegistrationCertificate`
* `addConwayStakeCredentialRegistrationAndDelegationCertificate`
* `addConwayStakeCredentialDeRegistrationCertificate`
* Add `addStakeScriptWitness` which adds a script stake address witness
in the transaction. This is a simplified version of `addStakeWitness`.
* Add Convex.Eon.IsShelleyToBabbageEra …
> Add transaction building functions for correctly adding registration deregistration and delegation certificates in Conway era.

- src/base/convex-base.cabal
- src/base/lib/Convex/PlutusLedger/V1.hs
- src/base/lib/Convex/PlutusLedger/V3.hs
- src/base/lib/Convex/Utils.hs
- src/base/test/Convex/PlutusLedgerSpec.hs
- src/optics/lib/Convex/CardanoApi/Lenses.hs
- src/un-ada/lib/UnAda/OffChain/Scripts.hs
- src/wallet/lib/Convex/Wallet/Operator.hs
* Remove lenses `_PlutusScriptWitnessV1`, `_PlutusScriptWitnessV2`, `_PlutusScriptWitnessV3`
* Add `_PlutusScriptWitness` lens
* Replace `Convex.PlutusLeger` module with `Convex.PlutusLedger.V1`
* Add `Convex.PlutusLedger.V3` module
> Expose PlutusV3-related functions

- .github/workflows/gh-pages.yaml
* Fixes the deprecation failure on github
> Bumps the version of upload-pages-artifact to 3.0.1

- src/base/lib/Convex/Class.hs
- src/blockfrost/lib/Convex/Blockfrost/Types.hs
- src/coin-selection/convex-coin-selection.cabal
- src/coin-selection/lib/Convex/CoinSelection.hs
- src/coin-selection/lib/Convex/Query.hs
- src/tx-mod/lib/Convex/TxMod/Cli.hs
* This will allow downstream functionality to create a hierarchy of errors that can be more easily handled.
* Added a note giving a short example on how to create such a hierarchy of errors.
* Individual functions have not been changed to the AsError pattern. This should be done later, if the changes here are useful downstream to minimize possibly wasted effort.
> Added classy prisms to error types.

- .github/workflows/ci-linux.yaml
- .github/workflows/nix.yaml
- flake.nix
- nix/project.nix
Allow to fetch derivation from cachix when available.
* Add substituers in `flake.nix`
* Update Nix to the latest version
* Difference concurrency Github action group between cabal run, and Nix run. Before, the same name name resulted in a conflict which prevented the Nix run to execute, thus the derivations would not be available in the Nix store.
> Update Nix version in CI, and add cachix substituters in `flake.nix`.

- src/base/lib/Convex/Class.hs
- src/base/lib/Convex/NodeQueries.hs
- src/blockfrost/lib/Convex/Blockfrost.hs
- src/blockfrost/lib/Convex/Blockfrost/MonadBlockchain.hs
- src/coin-selection/test/Spec.hs
- src/devnet/test/Spec.hs
- src/mockchain/lib/Convex/MockChain.hs
* Update `instance MonadBlockchain MockchainT`
* Update `instance MonadBlockchain BlockfrostT`: throws error because the Blockfrost Haskell API doesn't support querying stake addresses DRep voting.
> Add queryStakeVoteDelegatees in MonadBlockchain

- src/blockfrost/lib/Convex/Blockfrost.hs
Fix a bug in the blockfrost client where a 404 from the server (indicating empty address without utxo) is treated as an error. Instead we just return an empty list of utxos.
> Fix blockfrost behavior for empty addresses
